Algoritmo "FtoC"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : F para C
// Autor(a)    : Heberton Julio
// Data atual  : 03/09/2025
Var
// Seção de Declarações das variáveis 
F, C : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em Fahrenheit: ")
leia(F)
C <- (F-32) / 1.8
escreval(f, " Fahrenheit em C e: ", C)

Fimalgoritmo